[package]
name = "offset_calculator"
version = "0.1.0"
authors = ["Matthew \"Juniper\" Barlett <emeraldinspirations+asusrog839h+u1904@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
clap = "~2.12.1"
